[project]
name = "resume-analyzer"
version = "1.0.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "python-multipart",
    "PyPDF2",
    "python-dotenv",
    "google-generativeai",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"